### ISSUE TITLE
User deepend has custom in-game name

### ISSUE THREAD

**Issue by lunchdump** [butterscotchstallion/SpiffyRPG#54]
Currently, in-game names are correlated with user nicks. However, user `deepend` has a grandfathered custom in-game name "`dickface`," which provides `deepend` a veil of anonymity not afforded to other users. If a majority agrees, I would be willing accepting this disparity as an "early adopter bonus." In such case, I would suggest the bonus be extended to other users registered at a time earlier than or equal to that of user `deepend`.

**Comment by butterscotchstallion** [comment]
#3 should fix this

**Comment by lunchdump** [comment]
Oops, I scrolled through the enhancement reqs and missed this one.
