### ISSUE TITLE
RPSLV battle system

### ISSUE THREAD

**Issue by kerozene** [butterscotchstallion/SpiffyRPG#77]
# RPSLV battle system

Requires:
- items (weapons, health, shields)
- untransferrable items - base RPSLV weapons
- class template
  - class weapons theme
- possession transfer
- monsters have items

-----

## Initiation

Player attacks a monster or another player

- later mod: monsters can initiate

".b Player2"
".b Monster [weapon]"

- later mods:
  - (assumes monsters use random weapon) if you attack a monster without specifying weapon, choose the player's weapon randomly for each round
  - give monsters RPS/RPSLV AI

PVP: 
- target player must accept challenge within X time
  - players that are /away or .away don't appear on the map and can't be battled
- battle is decided by best of X rounds
  - later mod: number of rounds progresses with level of lowest participant

Monster:
- accepts all challenges
- battle is to the death

Participants each strike/attack once per round. Strikes against monsters can be sent publicly or by PM. Strikes against players are by PM.

".a &lt;weapon>"

If a player in a battle does not strike before the timeout, they forfeit the round.

- later mod:
  - players can .flee to abandon the battle, maybe taking an automatic hit

-----

Rounds are decided by the result of a rock-paper-scissors contest (actually rock-paper-scissors-lizard-spock - [rules](http://www.sheldonsfans.com/img_articles/original/102.jpg)). The winning side does damage to their opponent's HP. The damage is determined by the winner's level and any other modifiers.

- later mod ideas:
  - item: enchant weapon  - does extra damage if you win; works for a single RPS round
  - item: power weapon    - bypasses RPS contest (always hits or high % chance); destroyed after x uses
  - item: various shields - reduces the damage you take; destroyed after x uses

After the battle, some quantity of items are transferred to the winner.

- later mod:
  - an exceptional round gives a chance of instant possession transfer or opponent item loss

-----

## Class themes

Each player and monster class has its own names for each of the R,P,S,L,V weapons.

- later mod:
  - class bonus attack: e.g. Class X's Rock weapon does extra damage against Class Y

-----

### Stage 1
At level 1, players start with 1 weapon: Rock. Monsters start with Scissors. Therefore stage-1 players will always defeat stage-1 monsters, acquiring loot. Stage-1 players cannot participate in PVP battles. 

A stage-1 player attacking a stage >1 monster will lose the battle and die (R vs. RPS/RPSLV).

### Stage 2
At level X, players and monsters automatically acquire 2 more weapons (RPS). Players can now PVP against other stage-2 players in RPS mode. Stage-2 players cannot battle stage-1 monsters.

### Stage 3
At level Y, players and monsters automatically acquire 2 more weapons (RPSLV). Players can now (only) PVP against other stage-3 players, and can only attack stage-3 monsters.

**Comment by butterscotchstallion** [comment]
Moved to wiki https://github.com/butterscotchstallion/SpiffyRPG/wiki/Battle-System
