### ISSUE TITLE
Dungeon bosses

### ISSUE THREAD

**Issue by butterscotchstallion** [butterscotchstallion/SpiffyRPG#83]
- Each time a unit is slain, there is a 20% chance to raise/make hostile any bosses in the dungeon
- Bosses are named obviously, like "Rock Dude" and will play Rocks more than any other weapon (maybe 80%?)
- To balance that, they hit much harder and will likely kill anyone they strike

**Comment by lunchdump** [comment]
I say every 5-10 battles? Maybe every 3 battles between unique players, there are times i can kill 2 monsters in 1 minute if luck is on my side.

**Comment by butterscotchstallion** [comment]
Fixed
